### ISSUE TITLE
the same resources in subdirs are stored multiple times

### ISSUE THREAD

**Issue by lonestarr** [MKlimenko/embed#4]
Hi, congrats for your great work, but it seems that embed.exe stores dupes:

```
c:\MyDev\test>C:\MyDev\Contribs\embed-master\embed\x64\Release\embed.exe data -o src
embed.exe: saving data\a.txt
embed.exe: saving data\subdir\b.txt
embed.exe: saving data\subdir\c.txt
embed.exe: saving data\subdir\b.txt ... Skipped
embed.exe: saving data\subdir\c.txt ... Skipped
```

We can see that both subdir files are processed twice (this is the first run). And they appear twice too in the array is generated in resource_holder.hpp:

```
namespace {
class ResourceHolder {
private:
	std::array<Resource, 5> resources {
		Resource(resource_3021224534458533622,	resource_3021224534458533622_path),
		Resource(resource_9734938727009729610,	resource_9734938727009729610_path),
		Resource(resource_7710364344198624147,	resource_7710364344198624147_path),
		Resource(resource_9734938727009729610,	resource_9734938727009729610_path),
		Resource(resource_7710364344198624147,	resource_7710364344198624147_path),
	};
```

So there are 5 resources (including 2 dupes) for 3 input files...

**Comment by MKlimenko** [comment]
Hi there,

Good catch. Usually, this tool is used by passing the specific file paths instead of the whole folders, so this was undetected for some time. This was due to the recursive iteration for each of the subdirectories. It is fixed in 44eced8.
Try it out and feel free to reopen this issue if you have any issues.

All the best in the new year!

**Comment by lonestarr** [comment]
Thank you very much and happy new year too!

I've looked at your commit and the use of absolute path has led to an important regression: I can't use relative path anymore!
I mean in code like this:

```
void load_my_data(const char* file_path) {
#ifdef SHIPPING
    auto r =  resource_holder[file_path];
    ...
#else
    FILE* f = fopen(file_path);
    ...
#endif
} 
```

To make a code like this works with relative path (as it did) the absolute path should not be stored in the key to find the resource...
And maybe a better fix to the previous issue is just to check if a resource does not exist with the same path before adding a new one?

**Comment by MKlimenko** [comment]
I switched to absolute paths because I stored the full paths anyway and absolutes are shorter and less error-prone. Another thing I noticed is that on Windows it results in mixing the slashes, which is never a good thing.
For your use case, I'd suggest using `FindByFilename` method. I'll think about a way of working with both absolute and relative paths, but as a rule of thumb, absolute paths are more reliable.

**Comment by lonestarr** [comment]
Please do reconsider this.
I can't use FindByFilename since I may have different files having the same name in different subdirs...
So here is what I would do now, in pseudo-code:

```
void load_my_data(const char* file_path) {
#ifdef SHIPPING
    auto r =  resource_holder[make_absolute_path(build_machine_data_root, file_path)];
    ...
#else
    FILE* f = fopen(file_path);
    ...
#endif
} 
```
That means I have to store the build_machine_data_root in my code too, which is an extra step...

**Comment by MKlimenko** [comment]
The core problem here is that you have two different root folders: the one you build in (the root during compilation time) and the one you run in. You need to be extra careful when working with those two, that's why I suggest using the absolute paths. 
I've re-enabled the relative ones in bbeeed3, you can give it a try.
As for storing the `build_machine_data_root`, it's straightforward to do via CMake.

**Comment by lonestarr** [comment]
Thank you very much for your understanding!
It works now perfectly, all the best...
